<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Element is present]]>
    </line>
    <line>
      <![CDATA[Title is not Matching]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="64009" started-at="2017-08-17T14:37:12Z" finished-at="2017-08-17T14:38:16Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="64009" started-at="2017-08-17T14:37:12Z" finished-at="2017-08-17T14:38:16Z">
      <class name="com.automation.test.ValidLogin">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.automation.test.ValidLogin@9f9fb0]" name="openApplication" is-config="true" duration-ms="9966" started-at="2017-08-17T20:07:31Z" finished-at="2017-08-17T20:07:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="testValidLogin()[pri:0, instance:com.automation.test.ValidLogin@9f9fb0]" name="testValidLogin" duration-ms="13053" started-at="2017-08-17T20:07:40Z" finished-at="2017-08-17T20:07:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at generic.BasePage.verifyTitle(BasePage.java:23)
	at com.automation.test.ValidLogin.testValidLogin(ValidLogin.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Title is not Matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:com.automation.test.ValidLogin@9f9fb0]" name="closeApplication" is-config="true" duration-ms="870" started-at="2017-08-17T20:07:54Z" finished-at="2017-08-17T20:07:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.automation.test.ValidLogin -->
      <class name="com.automation.test.InvalidLogin">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.automation.test.InvalidLogin@135b478]" name="openApplication" is-config="true" duration-ms="12298" started-at="2017-08-17T20:07:12Z" finished-at="2017-08-17T20:07:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="PASS" signature="testInvalidLogin()[pri:0, instance:com.automation.test.InvalidLogin@135b478]" name="testInvalidLogin" duration-ms="5242" started-at="2017-08-17T20:07:24Z" finished-at="2017-08-17T20:07:29Z">
          <reporter-output>
            <line>
              <![CDATA[Element is present]]>
            </line>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:com.automation.test.InvalidLogin@135b478]" name="closeApplication" is-config="true" duration-ms="1099" started-at="2017-08-17T20:07:29Z" finished-at="2017-08-17T20:07:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.automation.test.InvalidLogin -->
      <class name="com.automation.test.verifyProductVersion">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:com.automation.test.verifyProductVersion@17c74e5]" name="openApplication" is-config="true" duration-ms="10074" started-at="2017-08-17T20:07:55Z" finished-at="2017-08-17T20:08:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="testProductVersion()[pri:0, instance:com.automation.test.verifyProductVersion@17c74e5]" name="testProductVersion" duration-ms="10446" started-at="2017-08-17T20:08:05Z" finished-at="2017-08-17T20:08:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [actiTIME 2017.1] but found [Product Version:]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [actiTIME 2017.1] but found [Product Version:]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.automation.page.EnterTimeTrackPage.verifyVersion(EnterTimeTrackPage.java:36)
	at com.automation.test.verifyProductVersion.testProductVersion(verifyProductVersion.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProductVersion -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:com.automation.test.verifyProductVersion@17c74e5]" name="closeApplication" is-config="true" duration-ms="731" started-at="2017-08-17T20:08:15Z" finished-at="2017-08-17T20:08:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- com.automation.test.verifyProductVersion -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
